spring.application.name=tienda-drm-jcgt-web

server.servlet.context-path=/tienda-tcg
# Configuración de conexión H2
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ejecuta data.sql solo después de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true

#Configuración de la consola Web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Permite ver la consola en navegadores modernos
spring.h2.console.settings.web-allow-others=true