# Nombre de la aplicación
spring.application.name=tienda-drm-jcgt-api

# CAMBIO DE PUERTO
server.port=8000

# Configuración de conexión H2 (Memoria compartida)
# Se usa el mismo nombre "shop" para que la API vea los mismos datos que la web si se ejecutan juntas
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 para la API
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Importante para que no choque con el frame de seguridad
spring.h2.console.settings.web-allow-others=true

# Ejecución de scripts iniciales
spring.jpa.defer-datasource-initialization=true

project.api.jwt.secret=YTM0ZGE3OTY4MDUyYmFiZGE0MzdlM2ZkNDU5ZGRhNTY0MTBlYjU0YmU0NTY3YmU5OTU0M2RjM2U1Y2I3M2I0Yg==

project.api.jwt.access-expiration=900000
project.api.jwt.refresh-expiration=86400000